### ISSUE TITLE
indented tree布局的顺序

### ISSUE THREAD

**Issue by nielinjie** [antvis/hierarchy#2]
发现indented布局（其他布局没有看过）的子节点顺序是从下到上的，当children数组中顺序是（0，1，2）的时候，布局节点从上到下是2，1，0，这点似乎与习惯不太一样。不知道这是个bug还是个feature。或者是否有一个配置可以配从上到下或从下到上。

* **Link**:
* **Platform**:
* **Mini Showcase(like screenshots)**:

**Comment by Yanyan-Wang** [comment]
#13

**Comment by Yanyan-Wang** [comment]
0.6.6 已解决
